// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdONtVe9jquFuKn1TrVZdCM4JQZbxhWxw',
    appId: '1:1045667958821:web:31bd05b07f43e87c3b6fcc',
    messagingSenderId: '1045667958821',
    projectId: 'kutuphane-36548',
    authDomain: 'kutuphane-36548.firebaseapp.com',
    storageBucket: 'kutuphane-36548.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4f8X96byuMkPMrbY4mMb9gfisjr99z34',
    appId: '1:1045667958821:android:562de8aec3e1fd1d3b6fcc',
    messagingSenderId: '1045667958821',
    projectId: 'kutuphane-36548',
    storageBucket: 'kutuphane-36548.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvSX2--MOcddf34vPeVfipJtHWA_x7HJE',
    appId: '1:1045667958821:ios:c282368c075a3ee23b6fcc',
    messagingSenderId: '1045667958821',
    projectId: 'kutuphane-36548',
    storageBucket: 'kutuphane-36548.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvSX2--MOcddf34vPeVfipJtHWA_x7HJE',
    appId: '1:1045667958821:ios:f1164ca47043b5c73b6fcc',
    messagingSenderId: '1045667958821',
    projectId: 'kutuphane-36548',
    storageBucket: 'kutuphane-36548.appspot.com',
    iosBundleId: 'com.example.kutuphaneOtomasyon.RunnerTests',
  );
}
